### ISSUE TITLE
Sindragosa

### ISSUE THREAD

**Issue by Nispodzianka** [Zidras/DBM-Icecrown#18]
I don't know if I can write about it here
is very helpful WA Sindragosa GPS https://wago.io/4rKqYpclz
it displays in a very clear way who and where should go with the beacon and we have a tts call with it
please implement this into DBM

I am including a file with tts call which I think are more explicit
[sound.zip](https://github.com/Zidras/DBM-Icecrown/files/6873658/sound.zip)

**Comment by Zidras** [comment]
Just pushed an implementation of this to the branch: https://github.com/Zidras/DBM-Icecrown/tree/Sindra-BeaconsDirections
This now adds a special warning with the direction you should go (Left, center, right) and a Voice call.
This is what I considered important. I will only push this once it's been tested on a Warmane raid scenario, so if you wish to speed up the process, test run it, otherwise you will have to wait for me to raid (which might take a while)

If you or someone else wishes to have all the names in LEFT CENTER RIGHT table in the screen, please do a Pull Request with it, since I don't find it that relevant with the table.concat already in place.

**Comment by Zidras** [comment]
FYI, one possible implementation is using info frame

**Comment by Zidras** [comment]
Implemented on https://github.com/Zidras/DBM-Icecrown/commit/fa381e2efa88e2c382f1c77e8774902f2432bb1b.
